query getUserUnstakedTokens($userId: ID!) {
  tokens(filter: { owner: { equalTo: $userId } }) {
    nodes {
      id
      owner
      rarity
      tokenURI
      isStaked
      stakedNFT {
        id
      }
    }
  }
}